/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export const medicalAbbreviations = [
   {
    "id": "arterial-blood-gases",
    "primaryAbbr": "ABG",
    "variants": [],
    "fullForm": "Arterial blood gases",
    "description": "A blood test that measures the acidity (pH) and the levels of oxygen and carbon dioxide in the blood from an artery.",
    "category": "Laboratory",
    "snomedCtId": "271329004",
    "icd10Code": "R79.81",
    "notes": "Used to detect lung diseases, monitor treatment for lung conditions, and check for severe kidney or metabolic problems."
  },
  {
    "id": "angiotensin-converting-enzyme",
    "primaryAbbr": "ACE",
    "variants": [],
    "fullForm": "Angiotensin converting enzyme",
    "description": "An enzyme that narrows blood vessels. Drugs called ACE inhibitors block this enzyme and are used to treat high blood pressure, heart failure, and diabetes-related kidney disease.",
    "category": "Pharmacology",
    "snomedCtId": "73586001",
    "icd10Code": "I10",
    "notes": "ACE inhibitors are a very common class of cardiovascular medication."
  },
  {
    "id": "anterior-cruciate-ligament",
    "primaryAbbr": "ACL",
    "variants": [],
    "fullForm": "Anterior cruciate ligament",
    "description": "A key ligament in the center of the knee that helps stabilize it. An ACL tear is a common sports injury.",
    "category": "Anatomy & Orthopedics",
    "snomedCtId": "362074003",
    "icd10Code": "S83.53",
    "notes": null
  },
  {
    "id": "attention-deficit-hyperactivity-disorder",
    "primaryAbbr": "ADHD",
    "variants": [],
    "fullForm": "Attention deficit hyperactivity disorder",
    "description": "A neurodevelopmental disorder characterized by persistent patterns of inattention, hyperactivity, and impulsivity.",
    "category": "Psychiatry",
    "snomedCtId": "406506008",
    "icd10Code": "F90.9",
    "notes": null
  },
  {
    "id": "atrial-fibrillation",
    "primaryAbbr": "AFIB",
    "variants": ["AF"],
    "fullForm": "Atrial fibrillation",
    "description": "An irregular and often rapid heart rate (arrhythmia) that can increase the risk of stroke, heart failure, and other heart-related complications.",
    "category": "Cardiology",
    "snomedCtId": "49436004",
    "icd10Code": "I48.91",
    "notes": null
  },
  {
    "id": "acquired-immunodeficiency-syndrome",
    "primaryAbbr": "AIDS",
    "variants": [],
    "fullForm": "Acquired immunodeficiency syndrome",
    "description": "The most advanced stage of infection with the Human Immunodeficiency Virus (HIV). It severely damages the immune system.",
    "category": "Infectious Disease",
    "snomedCtId": "62479008",
    "icd10Code": "B20",
    "notes": null
  },
  {
    "id": "alkaline-phosphatase",
    "primaryAbbr": "ALP",
    "variants": [],
    "fullForm": "Alkaline phosphatase",
    "description": "An enzyme found in high concentrations in the liver and bones. A blood test for ALP is often used to help detect liver or bone disease.",
    "category": "Laboratory",
    "snomedCtId": "104234003",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "amyotrophic-lateral-sclerosis",
    "primaryAbbr": "ALS",
    "variants": [],
    "fullForm": "Amyotrophic lateral sclerosis",
    "description": "A progressive neurodegenerative disease that affects nerve cells in the brain and the spinal cord. It is also known as Lou Gehrig's Disease.",
    "category": "Neurology",
    "snomedCtId": "86044005",
    "icd10Code": "G12.21",
    "notes": null
  },
  {
    "id": "alanine-aminotransferase",
    "primaryAbbr": "ALT",
    "variants": [],
    "fullForm": "Alanine aminotransferase",
    "description": "An enzyme found mostly in the liver. A blood test for ALT is used to detect liver injury or disease.",
    "category": "Laboratory",
    "snomedCtId": "104229001",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "age-related-macular-degeneration",
    "primaryAbbr": "AMD",
    "variants": [],
    "fullForm": "Age-related macular degeneration",
    "description": "A common eye condition and a leading cause of vision loss among people age 50 and older.",
    "category": "Ophthalmology",
    "snomedCtId": "192123005",
    "icd10Code": "H35.30",
    "notes": null
  },
  {
    "id": "acute-myocardial-infarction",
    "primaryAbbr": "AMI",
    "variants": ["MI"],
    "fullForm": "Acute myocardial infarction",
    "description": "The medical term for a heart attack, where blood flow to a part of the heart is blocked long enough to cause damage or death to the heart muscle.",
    "category": "Cardiology",
    "snomedCtId": "22298006",
    "icd10Code": "I21.9",
    "notes": null
  },
  {
    "id": "adult-onset-diabetes-mellitus",
    "primaryAbbr": "AODM",
    "variants": [],
    "fullForm": "Adult onset diabetes mellitus",
    "description": "An older term for Type 2 Diabetes, a chronic condition that affects the way the body processes blood sugar (glucose).",
    "category": "Endocrinology",
    "snomedCtId": "44054006",
    "icd10Code": "E11.9",
    "notes": "The term 'Type 2 Diabetes' is now preferred."
  },
  {
    "id": "aspartate-aminotransferase",
    "primaryAbbr": "AST",
    "variants": [],
    "fullForm": "Aspartate aminotransferase",
    "description": "An enzyme found in various tissues, including the liver and heart. A blood test for AST is often used to help detect liver damage.",
    "category": "Laboratory",
    "snomedCtId": "104230006",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "arteriovenous-malformation",
    "primaryAbbr": "AVM",
    "variants": [],
    "fullForm": "Arteriovenous malformation",
    "description": "A tangle of abnormal blood vessels connecting arteries and veins, disrupting normal blood flow. Most often occurs in the brain or spine.",
    "category": "Neurology & Vascular",
    "snomedCtId": "234226006",
    "icd10Code": "Q28.2",
    "notes": null
  },
  {
    "id": "bis-in-die",
    "primaryAbbr": "BID",
    "variants": ["b.i.d."],
    "fullForm": "Bis in die (Twice a day)",
    "description": "A medical instruction on a prescription indicating that a medication should be taken twice a day.",
    "category": "Pharmacology",
    "snomedCtId": "225756009",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "body-mass-index",
    "primaryAbbr": "BMI",
    "variants": [],
    "fullForm": "Body mass index",
    "description": "A measure of body fat based on height and weight that applies to adult men and women.",
    "category": "General & Preventive",
    "snomedCtId": "60621009",
    "icd10Code": "Z68",
    "notes": null
  },
  {
    "id": "blood-pressure",
    "primaryAbbr": "BP",
    "variants": [],
    "fullForm": "Blood pressure",
    "description": "The pressure of circulating blood against the walls of blood vessels. It's recorded as two numbers: systolic (when the heart beats) over diastolic (when the heart rests).",
    "category": "General & Preventive",
    "snomedCtId": "75367002",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "benign-prostatic-hypertrophy",
    "primaryAbbr": "BPH",
    "variants": [],
    "fullForm": "Benign prostatic hypertrophy",
    "description": "A noncancerous enlargement of the prostate gland, common in older men, which can cause urination difficulties.",
    "category": "Urology",
    "snomedCtId": "266567004",
    "icd10Code": "N40.1",
    "notes": null
  },
  {
    "id": "breast-cancer-gene",
    "primaryAbbr": "BRCA",
    "variants": [],
    "fullForm": "Breast Cancer Gene",
    "description": "Refers to the BRCA1 and BRCA2 genes. Mutations in these genes significantly increase the risk for breast and ovarian cancer.",
    "category": "Genetics & Oncology",
    "snomedCtId": "371905009",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "blood-urea-nitrogen",
    "primaryAbbr": "BUN",
    "variants": [],
    "fullForm": "Blood urea nitrogen",
    "description": "A blood test that measures the amount of urea nitrogen in the blood. It is a key indicator of kidney function.",
    "category": "Laboratory",
    "snomedCtId": "104240003",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "cancer",
    "primaryAbbr": "CA",
    "variants": [],
    "fullForm": "Cancer",
    "description": "A general term for a large group of diseases characterized by the uncontrolled growth and spread of abnormal cells.",
    "category": "Oncology",
    "snomedCtId": "363346000",
    "icd10Code": "C80.1",
    "notes": "Ambiguous abbreviation. Can also stand for 'Calcium'."
  },
  {
    "id": "calcium",
    "primaryAbbr": "CA",
    "variants": ["Ca"],
    "fullForm": "Calcium",
    "description": "A mineral essential for life. A blood calcium test measures the level of calcium in the blood.",
    "category": "Laboratory & Endocrinology",
    "snomedCtId": "104245008",
    "icd10Code": null,
    "notes": "Ambiguous abbreviation. Can also stand for 'Cancer'."
  },
  {
    "id": "cancer-antigen-125",
    "primaryAbbr": "CA-125",
    "variants": [],
    "fullForm": "Cancer antigen 125",
    "description": "A protein that is a tumor marker. A blood test for CA-125 may be used to monitor certain cancers, especially ovarian cancer.",
    "category": "Laboratory & Oncology",
    "snomedCtId": "104244002",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "coronary-artery-bypass-graft",
    "primaryAbbr": "CABG",
    "variants": [],
    "fullForm": "Coronary artery bypass graft",
    "description": "A type of heart surgery that improves blood flow to the heart by creating a new path for blood to travel around a blocked or narrowed coronary artery.",
    "category": "Cardiology & Surgery",
    "snomedCtId": "232717009",
    "icd10Code": "Z95.1",
    "notes": null
  },
  {
    "id": "coronary-artery-disease",
    "primaryAbbr": "CAD",
    "variants": [],
    "fullForm": "Coronary artery disease",
    "description": "The most common type of heart disease, caused by the buildup of plaque in the arteries that supply blood to the heart (atherosclerosis).",
    "category": "Cardiology",
    "snomedCtId": "53741008",
    "icd10Code": "I25.10",
    "notes": null
  },
  {
    "id": "computerized-axial-tomography",
    "primaryAbbr": "CAT",
    "variants": ["CT"],
    "fullForm": "Computerized axial tomography",
    "description": "An imaging procedure that uses special X-ray equipment to create detailed cross-sectional images of the body.",
    "category": "Radiology",
    "snomedCtId": "77170001",
    "icd10Code": null,
    "notes": "The term 'CT scan' is more commonly used today."
  },
  {
    "id": "complete-blood-count",
    "primaryAbbr": "CBC",
    "variants": [],
    "fullForm": "Complete blood count",
    "description": "A common blood test that evaluates the cells that circulate in blood, including red blood cells, white blood cells, and platelets.",
    "category": "Laboratory",
    "snomedCtId": "26604007",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "congenital-heart-disease",
    "primaryAbbr": "CHD",
    "variants": [],
    "fullForm": "Congenital heart disease",
    "description": "A general term for a range of birth defects that affect the normal way the heart works. The problem is present at birth.",
    "category": "Cardiology & Pediatrics",
    "snomedCtId": "13213009",
    "icd10Code": "Q24.9",
    "notes": null
  },
  {
    "id": "congestive-heart-failure",
    "primaryAbbr": "CHF",
    "variants": [],
    "fullForm": "Congestive heart failure",
    "description": "A chronic condition in which the heart doesn't pump blood as well as it should. Often simply called 'heart failure'.",
    "category": "Cardiology",
    "snomedCtId": "42343007",
    "icd10Code": "I50.9",
    "notes": null
  },
  {
    "id": "cytomegalovirus",
    "primaryAbbr": "CMV",
    "variants": [],
    "fullForm": "Cytomegalovirus",
    "description": "A common virus that can infect almost anyone. Most people don't know they have it because it rarely causes symptoms in healthy people.",
    "category": "Infectious Disease",
    "snomedCtId": "38723002",
    "icd10Code": "B25.9",
    "notes": null
  },
  {
    "id": "central-nervous-system",
    "primaryAbbr": "CNS",
    "variants": [],
    "fullForm": "Central nervous system",
    "description": "The part of the nervous system consisting of the brain and spinal cord.",
    "category": "Neurology & Anatomy",
    "snomedCtId": "118934005",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "chronic-obstructive-pulmonary-disease",
    "primaryAbbr": "COPD",
    "variants": [],
    "fullForm": "Chronic obstructive pulmonary disease",
    "description": "A chronic inflammatory lung disease that causes obstructed airflow from the lungs, making it difficult to breathe. Includes emphysema and chronic bronchitis.",
    "category": "Pulmonology",
    "snomedCtId": "13645005",
    "icd10Code": "J44.9",
    "notes": null
  },
  {
    "id": "creatine-phosphokinase",
    "primaryAbbr": "CPK",
    "variants": ["CK"],
    "fullForm": "Creatine phosphokinase",
    "description": "An enzyme found in the heart, brain, and skeletal muscle. A blood test for CPK (or CK) may be used to detect inflammation of muscles or heart muscle damage.",
    "category": "Laboratory",
    "snomedCtId": "104252009",
    "icd10Code": null,
    "notes": "CK (Creatine Kinase) is the more modern term."
  },
  {
    "id": "cardiopulmonary-resuscitation",
    "primaryAbbr": "CPR",
    "variants": [],
    "fullForm": "Cardiopulmonary resuscitation",
    "description": "An emergency lifesaving procedure performed when the heart stops beating. It involves chest compressions and often artificial ventilation.",
    "category": "Emergency Medicine",
    "snomedCtId": "85562002",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "chronic-renal-failure",
    "primaryAbbr": "CRF",
    "variants": [],
    "fullForm": "Chronic renal failure",
    "description": "A condition involving a gradual loss of kidney function over time.",
    "category": "Nephrology",
    "snomedCtId": "709044004",
    "icd10Code": "N18.9",
    "notes": "The term 'Chronic Kidney Disease' (CKD) is now more commonly used."
  },
  {
    "id": "c-reactive-protein",
    "primaryAbbr": "CRP",
    "variants": [],
    "fullForm": "C-reactive protein",
    "description": "A substance produced by the liver in response to inflammation. A CRP blood test is a marker for inflammation in the body.",
    "category": "Laboratory",
    "snomedCtId": "104254005",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "cerebrospinal-fluid",
    "primaryAbbr": "CSF",
    "variants": [],
    "fullForm": "Cerebrospinal fluid",
    "description": "A clear, colorless body fluid found in and around the brain and spinal cord.",
    "category": "Neurology & Anatomy",
    "snomedCtId": "119363000",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "cerebrovascular-accident",
    "primaryAbbr": "CVA",
    "variants": [],
    "fullForm": "Cerebrovascular accident",
    "description": "The medical term for a stroke, which is when blood flow to a part of your brain is stopped either by a blockage or the rupture of a blood vessel.",
    "category": "Neurology",
    "snomedCtId": "230690007",
    "icd10Code": "I64",
    "notes": null
  },
  {
    "id": "chest-x-ray",
    "primaryAbbr": "CXR",
    "variants": [],
    "fullForm": "Chest x-ray",
    "description": "A common diagnostic imaging test that uses a small dose of radiation to produce pictures of the structures inside the chest, such as the heart, lungs, and bones.",
    "category": "Radiology",
    "snomedCtId": "168952003",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "dilatation-and-curettage",
    "primaryAbbr": "D&C",
    "variants": [],
    "fullForm": "Dilatation and curettage",
    "description": "A surgical procedure involving the dilation of the cervix and scraping of the uterine lining (curettage).",
    "category": "Gynecology & Surgery",
    "snomedCtId": "72683001",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "degenerative-joint-disease",
    "primaryAbbr": "DJD",
    "variants": [],
    "fullForm": "Degenerative joint disease",
    "description": "Another name for osteoarthritis, the most common form of arthritis, caused by the breakdown of joint cartilage and underlying bone.",
    "category": "Orthopedics & Rheumatology",
    "snomedCtId": "396275006",
    "icd10Code": "M19.90",
    "notes": null
  },
  {
    "id": "diabetes-mellitus",
    "primaryAbbr": "DM",
    "variants": [],
    "fullForm": "Diabetes mellitus",
    "description": "A group of diseases that result in too much sugar in the blood (high blood glucose). The two main types are Type 1 and Type 2.",
    "category": "Endocrinology",
    "snomedCtId": "73211009",
    "icd10Code": "E11.9",
    "notes": null
  },
  {
    "id": "diphtheria-tetanus-pertussis",
    "primaryAbbr": "DTP",
    "variants": ["DTaP"],
    "fullForm": "Diphtheria, tetanus, pertussis",
    "description": "A combination vaccine that protects against three diseases: diphtheria, tetanus, and pertussis (whooping cough).",
    "category": "Immunology & Pediatrics",
    "snomedCtId": "396495009",
    "icd10Code": null,
    "notes": "DTaP is the formulation typically used in children."
  },
  {
    "id": "deep-vein-thrombosis",
    "primaryAbbr": "DVT",
    "variants": [],
    "fullForm": "Deep-vein thrombosis",
    "description": "A serious condition that occurs when a blood clot (thrombus) forms in one or more of the deep veins in the body, usually in the legs.",
    "category": "Vascular & Hematology",
    "snomedCtId": "128053003",
    "icd10Code": "I82.40",
    "notes": null
  },
  {
    "id": "diagnosis",
    "primaryAbbr": "DX",
    "variants": ["Dx"],
    "fullForm": "Diagnosis",
    "description": "The identification of the nature of an illness or other problem by examination of the symptoms.",
    "category": "General & Administrative",
    "snomedCtId": "276117006",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "electrocardiogram",
    "primaryAbbr": "ECG",
    "variants": ["EKG"],
    "fullForm": "Electrocardiogram",
    "description": "A simple test that can be used to check your heart's rhythm and electrical activity.",
    "category": "Cardiology",
    "snomedCtId": "164898009",
    "icd10Code": null,
    "notes": "EKG is a common variant in the US, from the German 'Elektrokardiogramm'."
  },
  {
    "id": "echocardiogram",
    "primaryAbbr": "ECHO",
    "variants": [],
    "fullForm": "Echocardiogram",
    "description": "A test that uses sound waves (ultrasound) to create moving pictures of the heart.",
    "category": "Cardiology & Radiology",
    "snomedCtId": "168962002",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "electroencephalogram",
    "primaryAbbr": "EEG",
    "variants": [],
    "fullForm": "Electroencephalogram",
    "description": "A test that detects electrical activity in your brain using small, metal discs (electrodes) attached to your scalp.",
    "category": "Neurology",
    "snomedCtId": "25256005",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "electromyography",
    "primaryAbbr": "EMG",
    "variants": [],
    "fullForm": "Electromyography",
    "description": "A diagnostic procedure to assess the health of muscles and the nerve cells that control them (motor neurons).",
    "category": "Neurology",
    "snomedCtId": "274531006",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "ear-nose-and-throat",
    "primaryAbbr": "ENT",
    "variants": [],
    "fullForm": "Ear, nose and throat",
    "description": "The medical specialty concerned with the diagnosis and treatment of disorders of the head and neck, including the ears, nose, and throat. Also known as Otolaryngology.",
    "category": "Otolaryngology",
    "snomedCtId": "394581000",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "endoscopic-retrograde-cholangiopancreatography",
    "primaryAbbr": "ERCP",
    "variants": [],
    "fullForm": "Endoscopic retrograde cholangiopancreatography",
    "description": "A procedure that combines upper gastrointestinal (GI) endoscopy and x-rays to treat problems of the bile and pancreatic ducts.",
    "category": "Gastroenterology & Radiology",
    "snomedCtId": "312582001",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "erythrocyte-sedimentation-rate",
    "primaryAbbr": "ESR",
    "variants": ["sed rate"],
    "fullForm": "Erythrocyte sedimentation rate",
    "description": "A type of blood test that measures how quickly erythrocytes (red blood cells) settle at the bottom of a test tube. A high ESR can indicate inflammation.",
    "category": "Laboratory",
    "snomedCtId": "104273001",
    "icd10Code": null,
    "notes": null
  },
  {
    "id": "end-stage-renal-disease",
    "primaryAbbr": "ESRD",
    "variants": [],
    "fullForm": "End-stage renal (kidney) disease",
    "description": "The last stage of chronic kidney disease, when the kidneys can no longer support the body's needs. The patient requires dialysis or a kidney transplant.",
    "category": "Nephrology",
    "snomedCtId": "46177005",
    "icd10Code": "N18.6",
    "notes": null
  }
];
