/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export const normalLabValues = [
  {
    id: 'lab_sodium',
    testName: 'Sodium',
    shortName: 'Na+',
    category: 'Electrolytes',
    normalRange: '135 - 145',
    unit: 'mEq/L (mmol/L)',
    description: 'Measures the level of sodium in the blood, crucial for fluid balance and nerve/muscle function.',
    notes: 'Critical values: <120 or >160 mEq/L.',
    criticalLow: '<120',
    criticalHigh: '>160',
  },
  {
    id: 'lab_potassium',
    testName: 'Potassium',
    shortName: 'K+',
    category: 'Electrolytes',
    normalRange: '3.5 - 5.0',
    unit: 'mEq/L (mmol/L)',
    description: 'Measures potassium levels, important for cell function, nerve signals, and muscle contractions, especially the heart.',
    notes: 'Critical values: <2.5 or >6.5 mEq/L.',
    criticalLow: '<2.5',
    criticalHigh: '>6.5',
  },
  {
    id: 'lab_chloride',
    testName: 'Chloride',
    shortName: 'Cl-',
    category: 'Electrolytes',
    normalRange: '98 - 107',
    unit: 'mEq/L (mmol/L)',
    description: 'Helps maintain fluid balance, blood volume, blood pressure, and body fluid pH.',
  },
  {
    id: 'lab_bicarbonate',
    testName: 'Bicarbonate',
    shortName: 'HCO3-',
    category: 'Electrolytes / Acid-Base',
    normalRange: '22 - 28',
    unit: 'mEq/L (mmol/L)',
    description: 'Measures the amount of bicarbonate, a form of CO2, in the blood; key for maintaining pH balance.',
  },
  {
    id: 'lab_bun',
    testName: 'Blood Urea Nitrogen',
    shortName: 'BUN',
    category: 'Renal Function',
    normalRange: '7 - 20',
    unit: 'mg/dL',
    description: 'Measures the amount of urea nitrogen in the blood, an indicator of kidney function.',
    notes: 'Equivalent to Urea 2.5 - 7.1 mmol/L. BUN/Creatinine ratio is often clinically useful.',
  },
  {
    id: 'lab_creatinine',
    testName: 'Creatinine',
    shortName: 'Cr',
    category: 'Renal Function',
    normalRange: '0.6 - 1.2 (Male), 0.5 - 1.1 (Female)',
    unit: 'mg/dL',
    description: 'Waste product from muscle metabolism, filtered by kidneys; indicator of kidney function.',
    notes: 'Approx. 53-106 µmol/L (Male), 44-97 µmol/L (Female). Varies with muscle mass.',
  },
  {
    id: 'lab_glucose_fasting',
    testName: 'Glucose, Fasting',
    shortName: 'FBG',
    category: 'Metabolic / Diabetes',
    normalRange: '70 - 99',
    unit: 'mg/dL',
    description: 'Measures blood sugar levels after an overnight fast, used to screen for diabetes.',
    notes: 'Impaired fasting glucose: 100-125 mg/dL. Diabetes: ≥126 mg/dL on two occasions.',
  },
  {
    id: 'lab_calcium',
    testName: 'Calcium, Total',
    shortName: 'Ca',
    category: 'Electrolytes / Bone',
    normalRange: '8.5 - 10.2',
    unit: 'mg/dL',
    description: 'Measures total calcium in the blood, vital for bone health, muscle function, nerve signaling, and blood clotting.',
    notes: 'Equivalent to 2.1-2.55 mmol/L. Correct for albumin levels if low (Corrected Ca = Measured Ca + 0.8 * (4.0 - Albumin)).',
  },
  {
    id: 'lab_albumin',
    testName: 'Albumin',
    category: 'Liver Function / Nutrition',
    normalRange: '3.5 - 5.0',
    unit: 'g/dL',
    description: 'Main protein in blood plasma, maintains oncotic pressure, transports hormones, drugs. Indicator of liver function and nutritional status.',
    notes: 'Equivalent to 35-50 g/L.',
  },
  {
    id: 'lab_total_protein',
    testName: 'Total Protein',
    category: 'Liver Function / Nutrition',
    normalRange: '6.0 - 8.3',
    unit: 'g/dL',
    description: 'Measures the total amount of albumin and globulin in the blood.',
  },
  {
    id: 'lab_ast',
    testName: 'Aspartate Aminotransferase',
    shortName: 'AST / SGOT',
    category: 'Liver Function',
    normalRange: '10 - 40',
    unit: 'U/L',
    description: 'Enzyme found in liver, heart, muscle. Elevated levels can indicate liver damage or other tissue injury.',
  },
  {
    id: 'lab_alt',
    testName: 'Alanine Aminotransferase',
    shortName: 'ALT / SGPT',
    category: 'Liver Function',
    normalRange: '7 - 56',
    unit: 'U/L',
    description: 'Enzyme mainly found in the liver. More specific indicator of liver damage than AST.',
  },
  {
    id: 'lab_alp',
    testName: 'Alkaline Phosphatase',
    shortName: 'ALP',
    category: 'Liver Function / Bone',
    normalRange: '44 - 147',
    unit: 'U/L',
    description: 'Enzyme related to the bile ducts and bone. Elevated levels can indicate liver disease, bile duct obstruction, or bone disorders.',
  },
  {
    id: 'lab_bilirubin_total',
    testName: 'Bilirubin, Total',
    category: 'Liver Function',
    normalRange: '0.1 - 1.2',
    unit: 'mg/dL',
    description: 'Product of heme breakdown, processed by the liver. Elevated levels cause jaundice.',
    notes: 'Equivalent to approx. 2-21 µmol/L.',
  },
  {
    id: 'lab_wbc',
    testName: 'White Blood Cell Count',
    shortName: 'WBC',
    category: 'Hematology',
    normalRange: '4,500 - 11,000',
    unit: 'cells/µL (or x10³/µL)',
    description: 'Measures the number of white blood cells, which fight infection.',
    notes: 'Equivalent to 4.5 - 11.0 x 10⁹/L.',
  },
  {
    id: 'lab_hemoglobin',
    testName: 'Hemoglobin',
    shortName: 'Hb / Hgb',
    category: 'Hematology',
    normalRange: 'Male: 13.5 - 17.5; Female: 12.0 - 15.5',
    unit: 'g/dL',
    description: 'Protein in red blood cells that carries oxygen from the lungs to the body\'s tissues.',
  },
  {
    id: 'lab_hematocrit',
    testName: 'Hematocrit',
    shortName: 'Hct',
    category: 'Hematology',
    normalRange: 'Male: 41 - 50; Female: 36 - 44',
    unit: '%',
    description: 'Percentage of blood volume occupied by red blood cells.',
  },
  {
    id: 'lab_platelets',
    testName: 'Platelet Count',
    shortName: 'Plt',
    category: 'Hematology',
    normalRange: '150,000 - 450,000',
    unit: 'cells/µL (or x10³/µL)',
    description: 'Small blood cells that help with clotting.',
    notes: 'Equivalent to 150 - 450 x 10⁹/L.',
  },
  {
    id: 'lab_tsh',
    testName: 'Thyroid Stimulating Hormone',
    shortName: 'TSH',
    category: 'Thyroid Function',
    normalRange: '0.4 - 4.0',
    unit: 'mIU/L (or µIU/mL)',
    description: 'Hormone from the pituitary gland that stimulates the thyroid gland. Key indicator of thyroid function.',
  },
  {
    id: 'lab_inr',
    testName: 'International Normalized Ratio',
    shortName: 'INR',
    category: 'Coagulation',
    normalRange: '0.8 - 1.1',
    unit: '',
    description: 'Standardized measure of prothrombin time (PT), used to monitor warfarin therapy.',
    notes: 'Therapeutic range for warfarin is typically 2.0-3.0, but varies by indication.',
  },
];
